# Problem Solving and Programming

## Day No.-  13

## Date: 16 May 19

## Day Outcomes:
* Functional Programming
* External Libraries
* File Handling/ Data Processing 

## Problem1:
  Define a function to read data from a text file.
### constraint:

### Test Case:
* 

In [4]:
def readFileData(filename):
    f = open(filename, 'r')
    filedata=f.read()
    #filedata += f.readline()
    
    
    f.close()
    return filedata

readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [2]:
def readFileData(filename):
    with open(filename, 'r') as f:
        #for line in f:
            #print(line, end='')
        
        print(f.read()) 
    
    
    return 

def writeIntoFile(filename, data):
    with open(filename, 'w') as f:
        f.write(data)
    return 

#readFileData('DataFiles/data.txt')
writeIntoFile('DataFiles/filewrite.txt','data written into fileWrite')

In [19]:
def writeIntoFile(filename, data, mode):
    with open(filename, mode) as f:
        f.write(data)
    return 

writeIntoFile('DataFiles/filewrite.txt','second line \n','a')

# Problem2:
  Function to generate a marks Data for 1300 students such that each mark is entered in a new line. Marks range from 0 to 100      (inclusive) as random numbers.
### constraint:

### Test Case:
* 

In [44]:
import random
def generateMarksData(n, filename):
    with open(filename, 'w') as marksfile:
        for i in range(0,n):
            marks = random.randint(0,100)
            marksfile.write(str(marks)+'\n')
            
    return

generateMarksData(1300, 'DataFiles/markdata.txt')


# Problem3:
  Generate a report on the marks data with the following indicators.
  
* Highest Mark:
* Lowest Mark:
* Average Mark:
* Number of student with distinction(>80):
* Number of student with first class(>60):
* Number of student with second class(>50):
* Number of student with third class(>40):
* number of student failed(<40):
### constraint:

### Test Case:
* 

In [20]:
import re
def readFileData1(filename,n):
    l=[]
    with open(filename, 'r') as f:
        for line in f:
            l.append(int(line))
        #print(l)
        print(max(l))
        print(min(l))
        print(sum(l)/n)
        count=0
        for i in l:
            if(i >= 80):
                count += 1
        print("students with distinction",count)
        count=0
        for i in l:
            if(i >= 60 and i<80):
                count += 1
        print("students with first clast ", count)
        count=0
        for i in l:
            if(i>=50 and i<60):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i>=40 and i<50):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i<40):
                count += 1
        print("students failed  ", count)
        
        

readFileData1('DataFiles/markdata.txt',1300)

100
0
49.997692307692304
students with distinction 265
students with first clast  250
students with second clast  133
students with second clast  129
students failed   523


In [19]:
import re, timeit
def generateMarksReport(marksfile):
    start = timeit.default_timer()
    markdata = readFileData(marksfile)
    markdata = re.split(r'\n',markdata)
    markdata = list(map(int, markdata[:len(markdata)-1]))
    #print(markdata[len(marksdate)-2])
    print(maxa(markdata))
    return timeit.default_timer()-start
generateMarksReport('DataFiles/markdata.txt')

48
55
40
80
32
92
94
38
18
54
32
96
53
66
78
88
66
70
62
25
6
54
69
50
30
50
51
19
71
22
16
67
50
12
3
53
16
15
14
41
74
59
66
80
71
76
99
49
64
73
14
31
64
47
1
66
78
60
78
59
31
93
4
16
28
23
62
74
24
67
45
91
38
30
31
60
83
46
86
62
87
91
76
27
65
27
67
59
42
6
74
19
35
98
79
26
11
91
25
100
99
27
31
50
99
100
42
88
90
84
38
99
72
30
88
73
94
71
48
54
78
19
7
65
55
88
96
20
65
93
45
87
86
15
52
32
54
67
56
89
66
17
12
74
82
95
41
96
48
27
35
56
6
88
30
96
28
95
37
60
82
76
51
63
51
26
33
86
1
42
79
49
33
80
87
19
35
82
60
14
28
2
92
22
49
99
10
26
79
4
37
25
27
85
23
64
65
0
41
62
93
93
69
57
24
49
98
40
66
25
15
74
98
25
55
75
23
49
61
57
98
4
23
53
66
51
9
30
59
5
100
44
10
17
30
48
37
92
75
68
5
91
7
99
39
42
69
25
9
42
16
85
0
88
66
29
59
38
70
81
16
95
45
56
29
1
80
68
61
47
84
58
66
65
3
46
100
25
48
97
11
4
86
20
67
70
11
10
52
31
42
86
5
7
22
48
79
55
53
91
4
80
30
58
30
76
15
17
86
70
72
39
50
22
33
96
74
51
58
6
95
16
85
34
85
42
55
53
52
12
45
35
62
54
94
68
53
15
60
46
6

TypeError: expected string or bytes-like object

### map example

In [18]:
import timeit
def square(n):
    return n*n

st = timeit.default_timer()
li = [1,2,3,4,5]
#s = str(li)
s=list(map(str,li))
s=[float(i)for i in s]
print(timeit.default_timer()-st)
s


0.00015980199987097876


[1.0, 2.0, 3.0, 4.0, 5.0]

In [26]:
import re
def readFileData1(filename,n):
    l=[]
    with open(filename, 'r') as f:
        for line in f:
            l.append(int(line))
        #print(l)
        print(max(l))
        print(min(l))
        print(sum(l)/n)
        count=0
        for i in l:
            if(i >= 80):
                count += 1
        print("students with distinction",count)
        count=0
        for i in l:
            if(i >= 60 and i<80):
                count += 1
        print("students with first clast ", count)
        count=0
        for i in l:
            if(i>=50 and i<60):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i>=40 and i<50):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i<40):
                count += 1
        print("students failed  ", count)
    return l
    
        

l=readFileData1('DataFiles/markdata.txt',1300)
def distinction(mark):
    return mark>=80

dis = sum(map(distinction,l))


100
0
49.997692307692304
students with distinction 265
students with first clast  250
students with second clast  133
students with second clast  129
students failed   523


In [25]:
def distinction(mark):
    return mark>=80

dis = sum(map(distinction,l))

failed = sum([1 for i in l if i<40])
failed

523

## NumPy

In [29]:
import numpy as np

a = np.array([[0, 1, 2],[3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [30]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(a+b)

[3 5 7]
