# Problem Solving and Programming

## Day No.-  13

## Date: 16 May 19

## Day Outcomes:
* Functional Programming
* External Libraries
* File Handling/ Data Processing 

## Problem1:
  Define a function to read data from a text file.
### constraint:

### Test Case:
* 

In [4]:
def readFileData(filename):
    f = open(filename, 'r')
    filedata=f.read()
    #filedata += f.readline()
    
    
    f.close()
    return filedata

readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [2]:
def readFileData(filename):
    with open(filename, 'r') as f:
        #for line in f:
            #print(line, end='')
        
        print(f.read()) 
    
    
    return 

def writeIntoFile(filename, data):
    with open(filename, 'w') as f:
        f.write(data)
    return 

#readFileData('DataFiles/data.txt')
writeIntoFile('DataFiles/filewrite.txt','data written into fileWrite')

In [19]:
def writeIntoFile(filename, data, mode):
    with open(filename, mode) as f:
        f.write(data)
    return 

writeIntoFile('DataFiles/filewrite.txt','second line \n','a')

# Problem2:
  Function to generate a marks Data for 1300 students such that each mark is entered in a new line. Marks range from 0 to 100      (inclusive) as random numbers.
### constraint:

### Test Case:
* 

In [44]:
import random
def generateMarksData(n, filename):
    with open(filename, 'w') as marksfile:
        for i in range(0,n):
            marks = random.randint(0,100)
            marksfile.write(str(marks)+'\n')
            
    return

generateMarksData(1300, 'DataFiles/markdata.txt')


# Problem3:
  Generate a report on the marks data with the following indicators.
  
* Highest Mark:
* Lowest Mark:
* Average Mark:
* Number of student with distinction(>80):
* Number of student with first class(>60):
* Number of student with second class(>50):
* Number of student with third class(>40):
* number of student failed(<40):
### constraint:

### Test Case:
* 

In [20]:
import re
def readFileData1(filename,n):
    l=[]
    with open(filename, 'r') as f:
        for line in f:
            l.append(int(line))
        #print(l)
        print(max(l))
        print(min(l))
        print(sum(l)/n)
        count=0
        for i in l:
            if(i >= 80):
                count += 1
        print("students with distinction",count)
        count=0
        for i in l:
            if(i >= 60 and i<80):
                count += 1
        print("students with first clast ", count)
        count=0
        for i in l:
            if(i>=50 and i<60):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i>=40 and i<50):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i<40):
                count += 1
        print("students failed  ", count)
        
        

readFileData1('DataFiles/markdata.txt',1300)

100
0
49.997692307692304
students with distinction 265
students with first clast  250
students with second clast  133
students with second clast  129
students failed   523


### map example

In [18]:
import timeit
def square(n):
    return n*n

st = timeit.default_timer()
li = [1,2,3,4,5]
#s = str(li)
s=list(map(str,li))
s=[float(i)for i in s]
print(timeit.default_timer()-st)
s


0.00015980199987097876


[1.0, 2.0, 3.0, 4.0, 5.0]

In [26]:
import re
def readFileData1(filename,n):
    l=[]
    with open(filename, 'r') as f:
        for line in f:
            l.append(int(line))
        #print(l)
        print(max(l))
        print(min(l))
        print(sum(l)/n)
        count=0
        for i in l:
            if(i >= 80):
                count += 1
        print("students with distinction",count)
        count=0
        for i in l:
            if(i >= 60 and i<80):
                count += 1
        print("students with first clast ", count)
        count=0
        for i in l:
            if(i>=50 and i<60):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i>=40 and i<50):
                count += 1
        print("students with second clast ", count)
        count=0
        for i in l:
            if(i<40):
                count += 1
        print("students failed  ", count)
    return l
    
        

l=readFileData1('DataFiles/markdata.txt',1300)
def distinction(mark):
    return mark>=80

dis = sum(map(distinction,l))


100
0
49.997692307692304
students with distinction 265
students with first clast  250
students with second clast  133
students with second clast  129
students failed   523


In [25]:
def distinction(mark):
    return mark>=80

dis = sum(map(distinction,l))

failed = sum([1 for i in l if i<40])
failed

523

## NumPy

In [29]:
import numpy as np

a = np.array([[0, 1, 2],[3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [30]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(a+b)

[3 5 7]
